name: Haskell-CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  generate-matrix:
    name: "Generate matrix from cabal"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract the tested GHC versions
        id: set-matrix
        uses: kleidukos/get-tested@v0.1.7.1
        with:
          cabal-file: champ.cabal
          ubuntu-version: "latest"
          macos-version: "latest"
          version: 0.1.7.1
  tests:
    name: ${{ matrix.ghc }} on ${{ matrix.os }}
    needs: generate-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v4
      - name: Set up Haskell
        id: setup-haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 'latest'
          cabal-update: false
    #   - name: Freeze
    #     run: cabal freeze
    #   - name: Cache
    #     uses: actions/cache@v4.2.1
    #     with:
    #       path: ${{ steps.setup-haskell.outputs.cabal-store }}
    #       key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-cabal-${{ hashFiles('**/plan.json') }}
    #       restore-keys: ${{ runner.os }}-ghc-${{ matrix.ghc }}-
      - name: Test
        run: cabal test all
